Repository deepin-community/kernel, pull requests merged in 2024-10, with the labels that each got.

#437 [Deepin-Kernel-SIG] deepin: OWNERS: Add winnscode to reviewers
  deepin/OWNERS
Labels: do-not-merge/invalid-owners-file

#441 net: mucse: initial support for rnp drivers from Mucse Technology
  arch/arm64/configs/deepin_arm64_desktop_defconfig
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
  drivers/net/ethernet/mucse/Kconfig
  drivers/net/ethernet/mucse/Makefile
  drivers/net/ethernet/mucse/rnp/Makefile
  drivers/net/ethernet/mucse/rnp/rnp.h
  drivers/net/ethernet/mucse/rnp/rnp_common.c
  drivers/net/ethernet/mucse/rnp/rnp_common.h
  drivers/net/ethernet/mucse/rnp/rnp_dcb.c
  drivers/net/ethernet/mucse/rnp/rnp_dcb.h
  drivers/net/ethernet/mucse/rnp/rnp_debugfs.c
  drivers/net/ethernet/mucse/rnp/rnp_ethtool.c
  drivers/net/ethernet/mucse/rnp/rnp_ethtool.h
  drivers/net/ethernet/mucse/rnp/rnp_lib.c
  drivers/net/ethernet/mucse/rnp/rnp_main.c
  drivers/net/ethernet/mucse/rnp/rnp_mbx.c
  drivers/net/ethernet/mucse/rnp/rnp_mbx.h
  drivers/net/ethernet/mucse/rnp/rnp_mbx_fw.c
  drivers/net/ethernet/mucse/rnp/rnp_mbx_fw.h
  drivers/net/ethernet/mucse/rnp/rnp_mpe.c
  drivers/net/ethernet/mucse/rnp/rnp_mpe.h
  drivers/net/ethernet/mucse/rnp/rnp_n10.c
  drivers/net/ethernet/mucse/rnp/rnp_param.c
  drivers/net/ethernet/mucse/rnp/rnp_pcs.c
  drivers/net/ethernet/mucse/rnp/rnp_pcs.h
  drivers/net/ethernet/mucse/rnp/rnp_phy.h
  drivers/net/ethernet/mucse/rnp/rnp_ptp.c
  drivers/net/ethernet/mucse/rnp/rnp_ptp.h
  drivers/net/ethernet/mucse/rnp/rnp_regs.h
  drivers/net/ethernet/mucse/rnp/rnp_sriov.c
  drivers/net/ethernet/mucse/rnp/rnp_sriov.h
  drivers/net/ethernet/mucse/rnp/rnp_sysfs.c
  drivers/net/ethernet/mucse/rnp/rnp_tc_u32_parse.h
  drivers/net/ethernet/mucse/rnp/rnp_type.h
  drivers/net/ethernet/mucse/rnp/version.h
Labels: needs-ok-to-test

#447 net: mucse: initial support for rnpgbevf drivers from Mucse Technology
  arch/arm64/configs/deepin_arm64_desktop_defconfig
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
  drivers/net/ethernet/mucse/Kconfig
  drivers/net/ethernet/mucse/Makefile
  drivers/net/ethernet/mucse/rnpgbevf/Makefile
  drivers/net/ethernet/mucse/rnpgbevf/defines.h
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf.h
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf_ethtool.c
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf_main.c
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf_mbx.c
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf_mbx.h
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf_regs.h
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf_sysfs.c
  drivers/net/ethernet/mucse/rnpgbevf/vf.c
  drivers/net/ethernet/mucse/rnpgbevf/vf.h
Labels: ok-to-test

#449 net: mucse: initial support for rnpvf driver from Mucse Technology
  arch/arm64/configs/deepin_arm64_desktop_defconfig
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
  drivers/net/ethernet/mucse/Kconfig
  drivers/net/ethernet/mucse/Makefile
  drivers/net/ethernet/mucse/rnpvf/Makefile
  drivers/net/ethernet/mucse/rnpvf/defines.h
  drivers/net/ethernet/mucse/rnpvf/ethtool.c
  drivers/net/ethernet/mucse/rnpvf/mbx.c
  drivers/net/ethernet/mucse/rnpvf/mbx.h
  drivers/net/ethernet/mucse/rnpvf/regs.h
  drivers/net/ethernet/mucse/rnpvf/rnpvf.h
  drivers/net/ethernet/mucse/rnpvf/rnpvf_main.c
  drivers/net/ethernet/mucse/rnpvf/sysfs.c
  drivers/net/ethernet/mucse/rnpvf/vf.c
  drivers/net/ethernet/mucse/rnpvf/vf.h
Labels: needs-ok-to-test
