Repository deepin-community/kernel, pull requests merged in 2024-08, with the labels that each got.

#348 Patch for audio function of glenfly arise chip.
  drivers/pci/quirks.c
  include/linux/pci_ids.h
Labels: needs-ok-to-test

#352 fs/ntfs3: Update log->page_{mask,bits} if log->page_size changed
  fs/ntfs3/fslog.c
Labels: lgtm

#358 [WIP] deepin: Add OWNERS for deepin kernel
  MAINTAINERS
  arch/loongarch/OWNERS
  arch/mips/OWNERS
  deepin/OWNERS
  drivers/OWNERS
  drivers/bluetooth/OWNERS
  drivers/gpu/OWNERS
  drivers/net/OWNERS
  mm/OWNERS
  net/OWNERS
  security/OWNERS
Labels: do-not-merge/work-in-progress, do-not-merge/invalid-owners-file

#260 [linux-6.6.y] USB:Fix kernel NULL pointer when unbind UHCI form vfio-pci
  drivers/usb/core/hcd-pci.c
Labels: needs-ok-to-test

#369 [linux-6.6.y] x86/mce: Add NMIs setup in machine_check func
  arch/x86/kernel/cpu/mce/core.c
Labels: needs-ok-to-test

#367 [linux-6.6.y] x86/mce/zhaoxin: Update mcelog to decode PCIE, ZDI/ZPI and DRAM errors
  arch/x86/include/asm/mce.h
  arch/x86/kernel/acpi/apei.c
  arch/x86/kernel/cpu/mce/apei.c
  drivers/acpi/apei/apei-base.c
  drivers/acpi/apei/ghes.c
  include/acpi/apei.h
Labels: needs-ok-to-test

#368 [linux-6.6.y] perf/x86/zhaoxin: fix warning log issue on KH-40000
  arch/x86/events/zhaoxin/core.c
  arch/x86/events/zhaoxin/uncore.c
  arch/x86/events/zhaoxin/uncore.h
Labels: needs-ok-to-test

#370 [linux-6.6.y] x86/hpet: Read HPET directly if panic in progress
  arch/x86/kernel/hpet.c
Labels: needs-ok-to-test

#373 [6.6]Hygon: Support reuse ASID feature for Hygon CSV
  arch/x86/kvm/Kconfig
  arch/x86/kvm/svm/csv.c
  arch/x86/kvm/svm/csv.h
  arch/x86/kvm/svm/sev.c
  include/uapi/linux/kvm.h
Labels: needs-ok-to-test

#387 [next] i2c/zhaoxin: switch i2c registration to devm functions
  drivers/i2c/busses/i2c-zhaoxin.c
Labels: needs-ok-to-test

#391 [linux-6.6.y] Fix built errors of Zhaoxin DMA patches for i386
  arch/x86/kernel/Makefile
  arch/x86/kernel/early-quirks.c
  arch/x86/kernel/zhaoxin_kh40000.c
  include/linux/dma-map-ops.h
Labels: needs-ok-to-test

#392 [linux-6.6.y] Fix a code logic error in Zhaoxin DMA patch
  arch/x86/kernel/zhaoxin_kh40000.c
Labels: needs-ok-to-test
