Repository deepin-community/kernel, pull requests merged in 2024-07, with the labels that each got.

#302 dt-bindings: phytnet_led: phytium: Add bindings for Phytium MAC led
  Documentation/devicetree/bindings/leds/phytnet_led.yaml
Labels: needs-ok-to-test

#148 Phytium PWM support
  Documentation/devicetree/bindings/pwm/phytium,pwm.yaml
  drivers/pwm/Kconfig
  drivers/pwm/Makefile
  drivers/pwm/pwm-phytium.c
  drivers/pwm/sysfs.c
Labels: ok-to-test

#276 [linux-6.6.y] Add support for ZXPAUSE instruction
  arch/x86/include/asm/cpufeature.h
  arch/x86/include/asm/cpufeatures.h
  arch/x86/include/asm/delay.h
  arch/x86/include/asm/disabled-features.h
  arch/x86/include/asm/msr-index.h
  arch/x86/include/asm/mwait.h
  arch/x86/include/asm/required-features.h
  arch/x86/include/asm/vmx.h
  arch/x86/include/asm/vmxfeatures.h
  arch/x86/kernel/cpu/Makefile
  arch/x86/kernel/cpu/centaur.c
  arch/x86/kernel/cpu/feat_ctl.c
  arch/x86/kernel/cpu/zhaoxin.c
  arch/x86/kernel/cpu/zxpause.c
  arch/x86/kernel/time.c
  arch/x86/kvm/cpuid.c
  arch/x86/kvm/reverse_cpuid.h
  arch/x86/kvm/vmx/capabilities.h
  arch/x86/kvm/vmx/vmcs.h
  arch/x86/kvm/vmx/vmx.c
  arch/x86/kvm/vmx/vmx.h
  arch/x86/kvm/x86.c
  arch/x86/lib/delay.c
  tools/arch/x86/include/asm/cpufeatures.h
  tools/arch/x86/include/asm/disabled-features.h
  tools/arch/x86/include/asm/msr-index.h
  tools/arch/x86/include/asm/required-features.h
Labels: ok-to-test

#305 fix: device 0x15d8 don't use AMD_DPM_FORCED_LEVEL_* except AMD_DPM_FO…
  drivers/gpu/drm/amd/pm/amdgpu_pm.c
Labels: ok-to-test

#253 [linux-6.6.y] Add support for Zhaoxin Processors
  arch/x86/include/asm/cpufeatures.h
  arch/x86/kernel/cpu/centaur.c
  arch/x86/kernel/cpu/zhaoxin.c
Labels: ok-to-test

#257 [linux-6.6.y] Add support for Zhaoxin HW Random Number Generator
  drivers/char/hw_random/Kconfig
  drivers/char/hw_random/Makefile
  drivers/char/hw_random/via-rng.c
  drivers/char/hw_random/zhaoxin-rng.c
Labels: lgtm, needs-ok-to-test

#261 [linux-6.6.y] iommu/vt-d: Add support for detecting ACPI namespace device in RMRR
  drivers/iommu/dma-iommu.c
  drivers/iommu/intel/dmar.c
  drivers/iommu/intel/iommu.c
  drivers/iommu/iommu.c
  include/linux/dmar.h
  include/linux/iommu.h
Labels: needs-ok-to-test

#268 [linux-6.6.y] Add support for Zhaoxin I2C controller
  drivers/i2c/busses/Kconfig
  drivers/i2c/busses/Makefile
  drivers/i2c/busses/i2c-zhaoxin.c
Labels: ok-to-test

#307 LoongArch: Add kernel livepatching support
  arch/loongarch/Kconfig
  arch/loongarch/Kconfig.debug
  arch/loongarch/Makefile
  arch/loongarch/include/asm/Kbuild
  arch/loongarch/include/asm/bug.h
  arch/loongarch/include/asm/exception.h
  arch/loongarch/include/asm/ftrace.h
  arch/loongarch/include/asm/module.h
  arch/loongarch/include/asm/orc_header.h
  arch/loongarch/include/asm/orc_lookup.h
  arch/loongarch/include/asm/orc_types.h
  arch/loongarch/include/asm/stackframe.h
  arch/loongarch/include/asm/thread_info.h
  arch/loongarch/include/asm/unwind.h
  arch/loongarch/include/asm/unwind_hints.h
  arch/loongarch/kernel/Makefile
  arch/loongarch/kernel/entry.S
  arch/loongarch/kernel/fpu.S
  arch/loongarch/kernel/genex.S
  arch/loongarch/kernel/lbt.S
  arch/loongarch/kernel/mcount_dyn.S
  arch/loongarch/kernel/module.c
  arch/loongarch/kernel/relocate_kernel.S
  arch/loongarch/kernel/rethook_trampoline.S
  arch/loongarch/kernel/setup.c
  arch/loongarch/kernel/stacktrace.c
  arch/loongarch/kernel/traps.c
  arch/loongarch/kernel/unwind_orc.c
  arch/loongarch/kernel/vmlinux.lds.S
  arch/loongarch/lib/clear_user.S
  arch/loongarch/lib/copy_user.S
  arch/loongarch/lib/memcpy.S
  arch/loongarch/lib/memset.S
  arch/loongarch/mm/tlb.c
  arch/loongarch/mm/tlbex.S
  arch/loongarch/vdso/Makefile
  include/linux/compiler.h
  scripts/Makefile
  tools/arch/loongarch/include/asm/inst.h
  tools/arch/loongarch/include/asm/orc_types.h
  tools/include/linux/bitops.h
  tools/objtool/Makefile
  tools/objtool/arch/loongarch/Build
  tools/objtool/arch/loongarch/decode.c
  tools/objtool/arch/loongarch/include/arch/cfi_regs.h
  tools/objtool/arch/loongarch/include/arch/elf.h
  tools/objtool/arch/loongarch/include/arch/special.h
  tools/objtool/arch/loongarch/orc.c
  tools/objtool/arch/loongarch/special.c
  tools/objtool/arch/x86/Build
  tools/objtool/arch/x86/orc.c
  tools/objtool/check.c
  tools/objtool/include/objtool/elf.h
  tools/objtool/include/objtool/orc.h
  tools/objtool/orc_dump.c
  tools/objtool/orc_gen.c
Labels: lgtm, approved, needs-ok-to-test

#277 [linux-6.6.y] ata: ahci: Add support for AHCI SGPIO Enclosure Management
  drivers/ata/Kconfig
  drivers/ata/Makefile
  drivers/ata/ahci_zhaoxin_sgpio.c
  drivers/ata/ahci_zhaoxin_sgpio.h
  drivers/ata/libahci.c
Labels: needs-ok-to-test

#272 [linux-6.6.y] Driver for Zhaoxin SM3 SM4 algorithms
  arch/x86/crypto/Kconfig
  arch/x86/crypto/Makefile
  arch/x86/crypto/sm3-zhaoxin-gmi.c
  arch/x86/crypto/sm4_zhaoxin_gmi.c
Labels: ok-to-test

#278 [linux-6.6.y] i2c: smbus: Add support for Zhaoxin SMBUS controller
  drivers/i2c/busses/Kconfig
  drivers/i2c/busses/Makefile
  drivers/i2c/busses/i2c-zhaoxin-smbus.c
Labels: needs-ok-to-test

#266 [linux-6.6.y] Turning off Zhaoxin ahci controller runtime pm from sysfs
  drivers/ata/ahci.c
Labels: needs-ok-to-test

#317 [linux-6.6.y] hwmon: zhaoxin-cputemp: add HWMON_THERMAL import
  drivers/hwmon/hwmon.c
Labels: needs-ok-to-test

#318 [linux-6.6.y] crypto: sm4-zhaoxin-gmi: Change file name
  arch/x86/crypto/sm4-zhaoxin-gmi.c
Labels: needs-ok-to-test

#282 [linux-6.6.y] x86/mce/zhaoxin: Enable mcelog to decode PCIE, ZDI/ZPI, and DRAM errors
  arch/x86/include/asm/mce.h
  arch/x86/kernel/acpi/apei.c
  arch/x86/kernel/cpu/mce/apei.c
  drivers/acpi/apei/apei-base.c
  drivers/acpi/apei/ghes.c
  include/acpi/apei.h
Labels: needs-ok-to-test

#288 [linux-6.6.y] efi: cper: Add Zhaoxin/Centaur ZDI/ZPI error decode
  drivers/firmware/efi/cper.c
  include/linux/cper.h
Labels: needs-ok-to-test

#308 net: macb: Add support for Phytium gem1.0 and gem 2.0
  Documentation/devicetree/bindings/net/cdns,macb.yaml
  drivers/net/ethernet/cadence/macb.h
  drivers/net/ethernet/cadence/macb_main.c
Labels: needs-ok-to-test

#331 [linux-6.6.y] hwmon: zhaoxin-rng: remove log when CPU mismatch
  drivers/char/hw_random/zhaoxin-rng.c
Labels: needs-ok-to-test

#280 [linux-6.6.y] iommu/dma: Fix not fully traversing iova reservations issue
  drivers/iommu/dma-iommu.c
Labels: needs-ok-to-test

#334 [linux6.6.y] pinctrl: zhaoxin: fix issues when builting into module
  drivers/pinctrl/zhaoxin/pinctrl-zhaoxin.c
Labels: needs-ok-to-test
