Repository deepin-community/kernel, pull requests merged in 2024-06, with the labels that each got.

#262 [linux-6.6.y] crypto: x86/crc32c-intel - Don't match some Zhaoxin CPUs
  arch/x86/crypto/crc32c-intel_glue.c
Labels: lgtm, ok-to-test

#267 [linux-6.6.y] Add MWAIT Cx support for Zhaoxin CPUs
  arch/x86/include/asm/acpi.h
  arch/x86/kernel/acpi/cstate.c
Labels: lgtm, ok-to-test

#269 LoongArch: Fix some issues and update interrupt registration policy
  arch/loongarch/include/asm/numa.h
  arch/loongarch/kernel/efi.c
  arch/loongarch/kernel/legacy_boot.h
  arch/loongarch/kernel/relocate.c
  drivers/irqchip/irq-loongson-eiointc.c
  drivers/irqchip/irq-loongson-pch-pic.c
Labels: lgtm, ok-to-test

#254 [linux-6.6.y] x86/mce: Add Centaur MCA support
  arch/x86/kernel/cpu/mce/core.c
  arch/x86/kernel/cpu/mce/intel.c
Labels: lgtm, ok-to-test

#279 [linux-6.6.y] x86/cpu: Remove pointless evaluation of x86_coreid_bits
  arch/x86/kernel/cpu/zhaoxin.c
Labels: lgtm, ok-to-test

#283 [linux-6.6.y] fs/address_space: move i_mmap_rwsem to mitigate a false sharing with i_mmap.
  include/linux/fs.h
Labels: lgtm, ok-to-test

#281 [linux-6.6.y] x86/mce: Set bios_cmci_threshold for CMCI threshold
  arch/x86/kernel/cpu/mce/core.c
Labels: lgtm, ok-to-test

#287 LoongArch: stmmac: Add Loongson platform support
  Documentation/networking/sfp-phylink.rst
  drivers/net/ethernet/stmicro/stmmac/common.h
  drivers/net/ethernet/stmicro/stmmac/dwmac-loongson.c
  drivers/net/ethernet/stmicro/stmmac/dwmac-sun8i.c
  drivers/net/ethernet/stmicro/stmmac/dwmac1000_dma.c
  drivers/net/ethernet/stmicro/stmmac/dwmac100_dma.c
  drivers/net/ethernet/stmicro/stmmac/dwmac4_core.c
  drivers/net/ethernet/stmicro/stmmac/dwmac4_dma.c
  drivers/net/ethernet/stmicro/stmmac/dwmac_dma.h
  drivers/net/ethernet/stmicro/stmmac/dwmac_lib.c
  drivers/net/ethernet/stmicro/stmmac/dwxgmac2_dma.c
  drivers/net/ethernet/stmicro/stmmac/hwif.h
  drivers/net/ethernet/stmicro/stmmac/stmmac_ethtool.c
  drivers/net/ethernet/stmicro/stmmac/stmmac_main.c
  drivers/net/phy/phylink.c
  include/linux/phylink.h
  include/linux/stmmac.h
Labels: lgtm, ok-to-test

#155 gpio: Add Phytium GPIO driver
  Documentation/devicetree/bindings/gpio/phytium,gpio.yaml
  MAINTAINERS
  drivers/gpio/Kconfig
  drivers/gpio/Makefile
  drivers/gpio/gpio-phytium-core.c
  drivers/gpio/gpio-phytium-core.h
  drivers/gpio/gpio-phytium-pci.c
  drivers/gpio/gpio-phytium-platform.c
Labels: lgtm, ok-to-test

#153 mailbox: Add support for Phytium SoC mailbox driver
  Documentation/devicetree/bindings/mailbox/phytium,mbox.yaml
  drivers/firmware/arm_scmi/mailbox.c
  drivers/mailbox/Kconfig
  drivers/mailbox/Makefile
  drivers/mailbox/phytium_mailbox.c
Labels: lgtm, needs-ok-to-test

#239 (linux-6.6.y) driver:crypto:add support for montage Mont-TSSE
  arch/x86/configs/deepin_x86_desktop_defconfig
  drivers/crypto/Kconfig
  drivers/crypto/Makefile
  drivers/crypto/montage/Kconfig
  drivers/crypto/montage/Makefile
  drivers/crypto/montage/tsse/Kconfig
  drivers/crypto/montage/tsse/Makefile
  drivers/crypto/montage/tsse/tsse_dev.h
  drivers/crypto/montage/tsse/tsse_dev_drv.c
  drivers/crypto/montage/tsse/tsse_dev_drv.h
  drivers/crypto/montage/tsse/tsse_dev_mgr.c
  drivers/crypto/montage/tsse/tsse_fw_service.c
  drivers/crypto/montage/tsse/tsse_fw_service.h
  drivers/crypto/montage/tsse/tsse_ipc.c
  drivers/crypto/montage/tsse/tsse_ipc.h
  drivers/crypto/montage/tsse/tsse_irq.c
  drivers/crypto/montage/tsse/tsse_irq.h
  drivers/crypto/montage/tsse/tsse_log.h
  drivers/crypto/montage/tsse/tsse_service.c
  drivers/crypto/montage/tsse/tsse_service.h
  drivers/crypto/montage/tsse/tsse_vuart.c
  drivers/crypto/montage/tsse/tsse_vuart.h
  drivers/crypto/montage/tsse/tsse_vuart_regs.h
Labels: lgtm, ok-to-test

#256 [linux-6.6.y] Add support for Zhaoxin Serial ATA IDE.
  drivers/ata/Kconfig
  drivers/ata/Makefile
  drivers/ata/sata_zhaoxin.c
Labels: lgtm, ok-to-test

#259 [linux-6.6.y] hwmon: Add support for Zhaoxin core temperature monitoring
  drivers/hwmon/Kconfig
  drivers/hwmon/Makefile
  drivers/hwmon/via-cputemp.c
  drivers/hwmon/zhaoxin-cputemp.c
Labels: lgtm, ok-to-test

#263 [linux-6.6.y] rtc: Fix set RTC time delay 500ms on some Zhaoxin SOCs
  drivers/rtc/rtc-mc146818-lib.c
Labels: lgtm, needs-ok-to-test, ok-to-test

#275 [linux-6.6.y] pinctrl: Add support Zhaoxin GPIO pinctrl
  drivers/pinctrl/Kconfig
  drivers/pinctrl/Makefile
  drivers/pinctrl/zhaoxin/Kconfig
  drivers/pinctrl/zhaoxin/Makefile
  drivers/pinctrl/zhaoxin/pinctrl-kx7000.c
  drivers/pinctrl/zhaoxin/pinctrl-zhaoxin.c
  drivers/pinctrl/zhaoxin/pinctrl-zhaoxin.h
Labels: lgtm, needs-ok-to-test, ok-to-test

#286 [linux-6.6.y] x86/perf: Add uncore performance events support for Zhaoxin CPU
  arch/x86/events/zhaoxin/Makefile
  arch/x86/events/zhaoxin/core.c
  arch/x86/events/zhaoxin/uncore.c
  arch/x86/events/zhaoxin/uncore.h
Labels: lgtm, ok-to-test

#273 [linux-6.6.y] cpufreq: ACPI: add ITMT support when CPPC enabled
  arch/x86/kernel/itmt.c
  drivers/cpufreq/acpi-cpufreq.c
  kernel/sched/topology.c
Labels: lgtm, needs-ok-to-test

#222 net: phytium: Add support for phytium GMAC
  Documentation/devicetree/bindings/net/phytmac.yaml
  drivers/net/ethernet/Kconfig
  drivers/net/ethernet/Makefile
  drivers/net/ethernet/phytium/Kconfig
  drivers/net/ethernet/phytium/Makefile
  drivers/net/ethernet/phytium/phytmac.h
  drivers/net/ethernet/phytium/phytmac_ethtool.c
  drivers/net/ethernet/phytium/phytmac_main.c
  drivers/net/ethernet/phytium/phytmac_pci.c
  drivers/net/ethernet/phytium/phytmac_platform.c
  drivers/net/ethernet/phytium/phytmac_ptp.c
  drivers/net/ethernet/phytium/phytmac_ptp.h
  drivers/net/ethernet/phytium/phytmac_v1.c
  drivers/net/ethernet/phytium/phytmac_v1.h
  drivers/net/ethernet/phytium/phytmac_v2.c
  drivers/net/ethernet/phytium/phytmac_v2.h
Labels: needs-ok-to-test

#292 scripts: package: adapt to UOS/deepin Secure Boot signing routine
  scripts/package/UEFI-CA-CERT/DEEPIN-UEFI-RSA.pem
  scripts/package/UEFI-CA-CERT/UOS-UEFI-RSA.pem
  scripts/package/builddeb
Labels: lgtm

#255 [linux-6.6.y] Add support for Zhaoxin HDAC
  sound/pci/hda/hda_controller.c
  sound/pci/hda/hda_controller.h
  sound/pci/hda/hda_intel.c
  sound/pci/hda/patch_hdmi.c
Labels: needs-ok-to-test

#290 add loongarch kvm support for Linux 6.6.y
  Documentation/virt/kvm/api.rst
  Documentation/virt/kvm/index.rst
  Documentation/virt/kvm/loongarch/hypercalls.rst
  Documentation/virt/kvm/loongarch/index.rst
  MAINTAINERS
  arch/loongarch/Kbuild
  arch/loongarch/Kconfig
  arch/loongarch/configs/loongson3_defconfig
  arch/loongarch/include/asm/Kbuild
  arch/loongarch/include/asm/hardirq.h
  arch/loongarch/include/asm/inst.h
  arch/loongarch/include/asm/irq.h
  arch/loongarch/include/asm/kvm_csr.h
  arch/loongarch/include/asm/kvm_host.h
  arch/loongarch/include/asm/kvm_mmu.h
  arch/loongarch/include/asm/kvm_para.h
  arch/loongarch/include/asm/kvm_types.h
  arch/loongarch/include/asm/kvm_vcpu.h
  arch/loongarch/include/asm/loongarch.h
  arch/loongarch/include/asm/paravirt.h
  arch/loongarch/include/asm/paravirt_api_clock.h
  arch/loongarch/include/asm/smp.h
  arch/loongarch/include/uapi/asm/Kbuild
  arch/loongarch/include/uapi/asm/kvm.h
  arch/loongarch/kernel/Makefile
  arch/loongarch/kernel/asm-offsets.c
  arch/loongarch/kernel/fpu.S
  arch/loongarch/kernel/irq.c
  arch/loongarch/kernel/paravirt.c
  arch/loongarch/kernel/perf_event.c
  arch/loongarch/kernel/smp.c
  arch/loongarch/kernel/time.c
  arch/loongarch/kvm/Kconfig
  arch/loongarch/kvm/Makefile
  arch/loongarch/kvm/exit.c
  arch/loongarch/kvm/interrupt.c
  arch/loongarch/kvm/main.c
  arch/loongarch/kvm/mmu.c
  arch/loongarch/kvm/switch.S
  arch/loongarch/kvm/timer.c
  arch/loongarch/kvm/tlb.c
  arch/loongarch/kvm/trace.h
  arch/loongarch/kvm/vcpu.c
  arch/loongarch/kvm/vm.c
  drivers/irqchip/irq-loongson-eiointc.c
  include/uapi/linux/kvm.h
Labels: lgtm, needs-ok-to-test

#159 ipmi: Add Phytium BT BMC driver support
  drivers/char/ipmi/Kconfig
  drivers/char/ipmi/Makefile
  drivers/char/ipmi/bt_bmc_phytium.c
Labels: needs-ok-to-test

#160 lpc: phytium: Add LPC snoop driver
  Documentation/devicetree/bindings/misc/phytium,lpc-snoop.yaml
  drivers/misc/Kconfig
  drivers/misc/Makefile
  drivers/misc/phytium-lpc-snoop.c
Labels: needs-ok-to-test

#161 drivers/perf: phytium: Support for Phytium Soc DDR controller PMU
  drivers/perf/Kconfig
  drivers/perf/Makefile
  drivers/perf/phytium/Kconfig
  drivers/perf/phytium/Makefile
  drivers/perf/phytium/phytium_ddr_pmu.c
  drivers/perf/phytium/phytium_pcie_pmu.c
Labels: needs-ok-to-test

#212 usb: phytium: Add support for Phytium USB controller
  Documentation/devicetree/bindings/usb/phytium,usb2.yaml
  drivers/usb/Kconfig
  drivers/usb/Makefile
  drivers/usb/phytium/Kconfig
  drivers/usb/phytium/Makefile
  drivers/usb/phytium/core.c
  drivers/usb/phytium/core.h
  drivers/usb/phytium/dma.c
  drivers/usb/phytium/dma.h
  drivers/usb/phytium/gadget.c
  drivers/usb/phytium/gadget.h
  drivers/usb/phytium/host.c
  drivers/usb/phytium/host_api.h
  drivers/usb/phytium/hw-regs.h
  drivers/usb/phytium/pci.c
  drivers/usb/phytium/platform.c
Labels: needs-ok-to-test

#265 [linux-6.6.y] x86/tsc: Make cur->adjusted values in package#1 to be the same
  arch/x86/kernel/tsc_sync.c
Labels: needs-ok-to-test

#152 gpio: Add Phytium SGPIO driver
  Documentation/devicetree/bindings/gpio/phytium,sgpio.yaml
  drivers/gpio/Kconfig
  drivers/gpio/Makefile
  drivers/gpio/gpio-phytium-sgpio.c
Labels: ok-to-test

#236 iommu/arm-smmu-v3: Add suspend and resume support
  drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.c
  drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.h
Labels: needs-ok-to-test

#299 arm64:phytnetled: phytium: Add link/act led driver for 10G mac
  drivers/char/Kconfig
  drivers/char/Makefile
  drivers/char/phytnetled/Kconfig
  drivers/char/phytnetled/Makefile
  drivers/char/phytnetled/phytnet_led.c
  drivers/char/phytnetled/phytnet_led.h
Labels: needs-ok-to-test
