Repository deepin-community/kernel, pull requests merged in 2025-03, with the labels that each got.

#641 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] deepin: mips: deepin_loongson3_desktop_defconfig: Enable EXFAT
  arch/mips/configs/deepin_loongson3_desktop_defconfig
Labels: approved, ok-to-test

#643 [6.6][bugfix]Hygon: Rename Hygon SM{3,4} feature macro to X86_FEATURE_HYGON_SM{3,4}
  arch/x86/include/asm/cpufeatures.h
Labels: lgtm, approved, ok-to-test

#644 deepin: config: check-config.yml: make check for arm64
  .github/workflows/check-config-arm64.yml
Labels: lgtm, approved

#653 AOSCOS: platform: x86: ideapad-laptop: add fixes for ThinkBook 14+ (2024 G6+)
  drivers/platform/x86/ideapad-laptop.c
Labels: approved

#656 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] deepin: config: enable fq_codel as default sched
  arch/arm64/configs/deepin_arm64_desktop_defconfig
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
  arch/mips/configs/deepin_loongson3_desktop_defconfig
  arch/s390/configs/deepin_s390x_z13_defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: approved

#669 [Deepin-Kernel-SIG] [linux 6.6-y] [Upstream] sched/psi: Optimise psi_group_change a bit
  kernel/sched/psi.c
Labels: approved

#664 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] Bluetooth: mediatek: use module param to disable isopkt by default
  drivers/bluetooth/btmtk.c
Labels: ok-to-test

#684 [Deepin-Kernel-SIG] [linux 6.6-y] [CIX] Kconfig: add arm64 depends for CIX
  drivers/clk/cix/Kconfig
  drivers/gpu/drm/cix/Kconfig
  drivers/phy/cix/Kconfig
  drivers/remoteproc/Kconfig
  drivers/soc/cix/Kconfig
  drivers/usb/cdns3/Kconfig
  sound/soc/cix/Kconfig
Labels: approved

#693 [Deepin-Kernel-SIG] [linux 6.6-y] perf/x86/uncore: Add DF PMU support for Hygon family 18h model 4h-8h and 10h
  arch/x86/events/amd/uncore.c
  arch/x86/include/asm/perf_event.h
Labels: lgtm, approved, ok-to-test

#696 PCI: Fix PCIe unplug Enumeration Long Blocking Issue
  drivers/pci/pci.c
Labels: lgtm, approved, ok-to-test
