Repository deepin-community/kernel, pull requests merged in 2025-07, with the labels that each got.

#909 scsi: leapioraid: add device and support fw log
  drivers/scsi/leapioraid/leapioraid_app.c
  drivers/scsi/leapioraid/leapioraid_func.c
  drivers/scsi/leapioraid/leapioraid_func.h
  drivers/scsi/leapioraid/leapioraid_os.c
  drivers/scsi/leapioraid/leapioraid_transport.c
Labels: lgtm, approved

#917 Driver supports HRDT trustraid D3100s controllers.
  drivers/scsi/Kconfig
  drivers/scsi/Makefile
  drivers/scsi/trustraid/Kconfig
  drivers/scsi/trustraid/Makefile
  drivers/scsi/trustraid/smartpqi.h
  drivers/scsi/trustraid/smartpqi_init.c
  drivers/scsi/trustraid/smartpqi_sas_transport.c
  drivers/scsi/trustraid/smartpqi_sis.c
  drivers/scsi/trustraid/smartpqi_sis.h
  drivers/scsi/trustraid/trustrlib.c
  drivers/scsi/trustraid/trustrlib.h
Labels: lgtm, approved, ok-to-test

#898 [bugfix][6.6] fix soft lockup warning in psp_mutex_lock_timeout()
  drivers/crypto/ccp/hygon/psp-dev.c
Labels: ok-to-test

#969 drm/amd/display: dont subst v without RISCV_ISA_V
  drivers/gpu/drm/amd/display/dc/dml/Makefile
Labels: approved

#979 iommu: smmuv3: Not print information of SMMU 0x10 event
  arch/arm64/include/asm/cputype.h
  drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.c
  drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.h
Labels: approved
