Repository deepin-community/kernel, pull requests merged in 2025-04, with the labels that each got.

#719 [Deepin-Kernel-SIG] [linux 6.6-y] [FROMLIST] Bluetooth: Revert vendor-specific ISO classification for no…
  drivers/bluetooth/btintel.c
  include/net/bluetooth/hci_core.h
  net/bluetooth/hci_core.c
Labels: approved

#714 [Deepin-Kernel-SIG] [linux 6.6-y] [Upstream] x86/platform: Only allow CONFIG_EISA for 32-bit
  arch/x86/Kconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: approved

#723 config: enable CAN
  arch/mips/configs/deepin_loongson3_desktop_defconfig
  arch/s390/configs/deepin_s390x_z13_defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: approved

#724 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] config: deepin_x86_desktop_defconfig: recover enable FB_EFI
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: approved

#725 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] config: deepin_x86_desktop_defconfig: recover enable FRAMEBUFFER_CONS…
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: approved

#726 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] config: enable sched_debug and slub_debug
  arch/arm64/configs/deepin_arm64_desktop_defconfig
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
  arch/mips/configs/deepin_loongson3_desktop_defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: approved

#727 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] CI: check-config: update generic config whitelist
  .github/workflows/generic_config_whitelist
Labels: approved

#731 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] fix x86 defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: approved

#732 KVM: SVM: CSV: Return 0 at the beginning of csv_guest_hygon_coco_exte…
  arch/x86/kvm/svm/csv.c
Labels: approved, needs-ok-to-test

#742 nand: phytium: Resolved a call trace warning message
  drivers/mtd/nand/raw/phytium_nand.c
  drivers/mtd/nand/raw/phytium_nand_pci.c
  drivers/mtd/nand/raw/phytium_nand_plat.c
Labels: lgtm, approved, needs-ok-to-test

#747 net/stmmac: Add pm ops for phytium dwmac driver
  drivers/net/ethernet/stmicro/stmmac/dwmac-phytium.c
Labels: lgtm, approved, needs-ok-to-test
