Repository deepin-community/kernel, pull requests merged in 2025-01, with the labels that each got.

#548 [Deepin-Kernel-SIG] [linux 6.6-y] deepin: config: adjust PSI and RCU config
  arch/arm64/configs/deepin_arm64_desktop_defconfig
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
  arch/x86/configs/deepin_x86_desktop_defconfig
Labels: lgtm

#550 [Deepin-Kernel-SIG] [linux 6.6-y] config: deepin_loongarch_desktop_defconfig: Disable CONFIG_DRM_LEGACY
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
Labels: lgtm, approved

#553 [linux-6.6.y] cpufreq: export sched_set_itmt_support and sched_set_itmt_core_prio
  arch/x86/kernel/itmt.c
Labels: lgtm, needs-ok-to-test

#571 scsi: leapioraid: update leapioraid driver version
  drivers/scsi/leapioraid/leapioraid_func.h
Labels: lgtm
