Repository deepin-community/kernel, pull requests merged in 2025-05, with the labels that each got.

#745 phytium: macb update to phytium 6.6.0.2 version
  drivers/net/ethernet/cadence/macb_main.c
Labels: needs-ok-to-test

#778 dt-bindings: PCI: phytium: Fix maxItems value
  Documentation/devicetree/bindings/pci/phytium,pd2008-pcie-ep.yaml
Labels: needs-ok-to-test

#757 phytium: tacho update to phytium 6.6.0.2 version
  drivers/hwmon/tacho-phytium.c
Labels: ok-to-test

#759 pwm:phytium: Add PWM driver version messages
  drivers/pwm/pwm-phytium.c
Labels: lgtm, approved, needs-ok-to-test

#752 Base_ctrl: phytium: Add driver for base controller
  drivers/acpi/Kconfig
  drivers/acpi/Makefile
  drivers/acpi/phytium_base_ctrl.c
  drivers/acpi/phytium_base_ctrl.h
Labels: approved

#766 can: phytium: Update support for Phytium Can controller driver
  drivers/net/can/phytium/phytium_can.c
Labels: needs-ok-to-test

#770 media: phytium-jpeg: Fixed some JPEG driver issues
  drivers/media/platform/phytium/phytium_jpeg_core.c
  drivers/media/platform/phytium/phytium_jpeg_core.h
Labels: lgtm, approved, needs-ok-to-test

#776 [linux-6.6.y][Feature]Hygon: In a CSV3 VM, the hypercall should notify real page enc/dec status
  arch/x86/kernel/kvm.c
Labels: lgtm, approved, needs-ok-to-test

#771 hda: phytium: update phytium hda controller driver support
  sound/pci/hda/hda_phytium.c
Labels: ok-to-test

#783 bcache: call force_wake_up_gc() if necessary in check_should_bypass()
  drivers/md/bcache/request.c
Labels: ok-to-test

#788 [Deepin Kernel SIG] [Intel] dmaengine: idxd: Add a new DSA device ID for Granite Rapids-D platform
  drivers/dma/idxd/init.c
  include/linux/pci_ids.h
Labels: approved

#789 [Deepin Kernel SIG] [Intel] 6.6: x86/cpu: KVM: Advertise CPUIDs for new instructions in Clearwater Forest (CWF)
  arch/x86/include/asm/cpufeatures.h
  arch/x86/kvm/cpuid.c
  arch/x86/kvm/reverse_cpuid.h
Labels: approved

#795 [Deepin Kernel SIG] Revert "staging: remove ashmem"
  drivers/staging/Kconfig
  drivers/staging/Makefile
  drivers/staging/android/Kconfig
  drivers/staging/android/Makefile
  drivers/staging/android/TODO
  drivers/staging/android/ashmem.c
  drivers/staging/android/ashmem.h
  drivers/staging/android/uapi/ashmem.h
Labels: approved

#806 eth: mucse: Fix rx PAGE error in csum handler
  drivers/net/ethernet/mucse/rnp/rnp_main.c
  drivers/net/ethernet/mucse/rnpgbe/rnpgbe_main.c
  drivers/net/ethernet/mucse/rnpgbevf/rnpgbevf_main.c
  drivers/net/ethernet/mucse/rnpvf/rnpvf_main.c
Labels: lgtm, ok-to-test

#809 cpufreq: phytium: bugfix the null pointer of boost in high temperature
  drivers/cpufreq/cpufreq.c
Labels: needs-ok-to-test

#814 [linux-6.6.y][Bugfix]hugetlb: Fix NULL pointer dereference BUG
  mm/hugetlb.c
Labels: approved, needs-ok-to-test

#825 [Deepin-Kernel-SIG] [linux 6.6-y] [Deepin] deepin: deepin_loongarch_desktop_defconfig: disable irqsoff_tracer
  arch/loongarch/configs/deepin_loongarch_desktop_defconfig
Labels: lgtm, approved, ok-to-test
