Repository deepin-community/kernel, pull requests merged in 2025-06, with the labels that each got.

#869 riscv:defconfig: enable zstd/xz support for fw loader
  arch/riscv/configs/deepin_riscv64_desktop_defconfig
Labels: approved

#878 [Deepin-Kernel-SIG] [linux 6.6-y] 修复 ARM64 架构下 HAOC 启用时可能出现的休眠后崩溃问题
  arch/arm64/include/asm/haoc/iee-asm.h
  arch/arm64/include/asm/haoc/iee-si.h
  arch/arm64/include/asm/mmu_context.h
  arch/arm64/kernel/haoc/iee/iee-gate.S
  arch/arm64/kernel/haoc/iee/iee-init.c
  arch/arm64/kernel/haoc/iee/iee-mmu.c
  arch/arm64/kernel/haoc/iee/iee-si-gate.S
  arch/arm64/kernel/haoc/iee/iee-si.c
  arch/arm64/mm/context.c
Labels: ok-to-test

#886 [Deepin-Kernel-SIG] [linux 6.6-y] [Upstream] wifi: mt76: mt7921: introduce mt7920 PCIe support
  drivers/net/wireless/mediatek/mt76/mt76_connac.h
  drivers/net/wireless/mediatek/mt76/mt7921/pci.c
  drivers/net/wireless/mediatek/mt76/mt792x.h
Labels: ok-to-test

#910 symbols: Export symbols needed by Android Drivers
  fs/file.c
  kernel/sched/syscalls.c
Labels: approved, ok-to-test
