Repository deepin-community/kernel, pull requests merged in 2025-08, with the labels that each got.

#1007 deepin: KABI:block: kabi: KABI reservation for blk-cgroup
  block/blk-cgroup.h
  include/linux/blkdev.h
Labels: needs-ok-to-test

#1005 deepin: KABI: dax: kabi: Reserve KABI slots for dax_* struct
  drivers/dax/super.c
  include/linux/dax.h
Labels: needs-ok-to-test

#1008 deepin:KABI:nvme: kabi: KABI reservation for nvme_ctrl
  drivers/nvme/host/nvme.h
Labels: needs-ok-to-test

#1013 deepin: KABI:drm: drm_connector.h: Add DEEPIN_KABI_RESERVE
  include/drm/drm_connector.h
Labels: needs-ok-to-test

#1017 deepin: KABI:kabi: reserve space for struct clocksource
  include/linux/clocksource.h
Labels: needs-ok-to-test

#1018 deepin: KABI:kabi: bus_type, device_driver, dev_pm_ops reservation
  include/linux/device/bus.h
  include/linux/pm.h
Labels: needs-ok-to-test

#1021 deepin: KABI:kabi: reserve space for fb.h
  include/linux/fb.h
Labels: needs-ok-to-test

#1020 deepin: KABI:exportfs: kabi: Reserve KABI slots for export_operations…
  include/linux/exportfs.h
Labels: needs-ok-to-test

#1015 deepin: KABI:kabi: reserve space for bpf related structures
  include/linux/bpf.h
  include/linux/bpf_local_storage.h
  include/linux/bpf_verifier.h
Labels: needs-ok-to-test

#1025 deepin: KABI:kabi: reserve space for struct irq_work
  include/linux/irq_work.h
Labels: needs-ok-to-test

#1024 deepin: KABI:irq_desc: Add kabi_reserve in irq_desc
  include/linux/irqdesc.h
Labels: needs-ok-to-test

#1030 deepin: KABI:ata: libata: reserve space for structures in libata
  include/linux/libata.h
Labels: needs-ok-to-test

#1032 deepin: KABI:mmc: kabi: KABI reservation for mmc
  include/linux/mmc/card.h
  include/linux/mmc/host.h
Labels: needs-ok-to-test

#1036 deepin: KABI:KABI: Reserve space for struct module
  include/linux/module.h
Labels: needs-ok-to-test

#1050 deepin: KABI:sysfs: kabi: Reserve KABI slots for bin_attribute struct
  include/linux/sysfs.h
Labels: needs-ok-to-test

#1051 deepin: KABI:energy_model: Add DEEPIN_KABI_RESERVE
  include/linux/energy_model.h
Labels: needs-ok-to-test

#1058 deepin: KABI:cgroup_bpf/kabi: reserve space for cgroup_bpf related st…
  include/linux/bpf-cgroup-defs.h
Labels: needs-ok-to-test

#1059 deepin: KABI:interrupt: Add DEEPIN_KABI_RESERVE in interrupt.h
  include/linux/interrupt.h
Labels: needs-ok-to-test

#1060 deepin: KABI:irqdomain: Add DEEPIN_KABI_RESERVE in irqdomain
  include/linux/irqdomain.h
Labels: needs-ok-to-test

#1062 deepin: KABI:nvmet-fc: kabi: KABI reservation for nvme_fc_port_template
  include/linux/nvme-fc-driver.h
Labels: needs-ok-to-test

#1064 deepin: KABI:quota: kabi: KABI reservation for quota
  include/linux/quota.h
Labels: needs-ok-to-test

#1065 deepin: KABI:iov_iter: kabi: KABI reservation for iov_iter
  include/linux/uio.h
Labels: needs-ok-to-test

#1066 deepin: KABI:kabi: reserve space for struct timer_list
  include/linux/timer.h
Labels: needs-ok-to-test

#1076 deepin: KABI:kabi: reserve space for posix clock related structure
  include/linux/posix-clock.h
Labels: needs-ok-to-test

#1081 deepin: KABI:mtd: kabi: Reserve KABI slots for mtd_device_xxx_registe…
  include/linux/mtd/mtd.h
  include/linux/mtd/partitions.h
Labels: needs-ok-to-test

#1079 deepin: KABI:kabi: reserve space for workqueue subsystem related stru…
  include/linux/workqueue.h
Labels: needs-ok-to-test

#1071 deepin: KABI:kabi: reserve space for struct cpu_stop_work
  include/linux/stop_machine.h
Labels: needs-ok-to-test

#1073 deepin: KABI:ipmi: kabi: KABI reservation for ipmi
  drivers/char/ipmi/ipmi_msghandler.c
  include/linux/ipmi.h
  include/linux/ipmi_smi.h
Labels: needs-ok-to-test

#1057 deepin: KABI:namespace: kabi: reserve for future namespace development
  include/linux/pid_namespace.h
  include/linux/user_namespace.h
  kernel/ucount.c
Labels: approved, needs-ok-to-test

#1061 deepin: KABI:cgroup/misc: reserve kabi for future misc development
  include/linux/misc_cgroup.h
Labels: needs-ok-to-test

#1087 deepin: KABI:scsi: iscsi: kabi: KABI reservation for iscsi_transport
  include/scsi/scsi_transport_iscsi.h
Labels: needs-ok-to-test

#1092 deepin: KABI:kabi: net: reserve space for net can subsystem related s…
  include/net/netns/can.h
Labels: needs-ok-to-test

#1091 deepin: KABI:kabi: net: reserve space for net netfilter subsystem rel…
  include/linux/netfilter/ipset/ip_set.h
  include/linux/netfilter/nfnetlink.h
  include/net/netns/netfilter.h
Labels: needs-ok-to-test

#1088 deepin: KABI:kabi: reserve space for struct acpi_device and acpi_scan…
  include/acpi/acpi_bus.h
Labels: needs-ok-to-test

#1067 deepin: KABI:kabi: net: reserve space for net related structure
  include/linux/netlink.h
  include/net/cfg802154.h
  include/net/inet_frag.h
  include/net/ip_fib.h
  include/net/ipv6_stubs.h
  include/net/netns/conntrack.h
  include/net/netns/core.h
  include/net/xfrm.h
Labels: needs-ok-to-test

#1100 deepin: KABI:drm: Add kabi reserve in drm_modeset_lock.h
  include/drm/drm_modeset_lock.h
Labels: approved, needs-ok-to-test

#1097 deepin: KABI:kabi: net: reserve space for xdp subsystem related struc…
  include/net/xdp.h
Labels: approved, needs-ok-to-test

#1122 [Deepin-Kernel-SIG] [linux 6.6-y] [Upstream] sched/fair: Remove unused parameter from sched_asym()
  kernel/sched/fair.c
Labels: approved

#1086 deepin: KABI:kabi: net: reserve space for net base subsystem related …
  include/linux/device.h
  include/net/flow_dissector.h
  include/net/genetlink.h
  include/net/inet_connection_sock.h
  include/net/ip6_fib.h
  include/net/neighbour.h
  include/net/netdev_rx_queue.h
  include/net/netns/ipv6.h
  include/net/netns/nftables.h
  include/net/netns/xfrm.h
  include/net/page_pool/types.h
  include/net/sch_generic.h
  include/net/tls.h
  include/net/xsk_buff_pool.h
  net/devlink/devl_internal.h
Labels: needs-ok-to-test

#1102 deepin: KABI:kabi: net: reserve space for net rdma subsystem related …
  include/rdma/ib_addr.h
  include/rdma/rdma_cm.h
  include/rdma/rdma_counter.h
  include/rdma/rdma_vt.h
Labels: needs-ok-to-test

#1104 deepin: KABI:kabi: reserve space for struct ptp_clock
  drivers/ptp/ptp_private.h
Labels: approved, needs-ok-to-test
